### ISSUE TITLE
Запуск wolfram из командной строки debian

### ISSUE THREAD

**Issue by reverse-cat** [KirillBelovTest/MathematicaSimpleServer#1]
Привет. Я только начал учить Wolfram на основе твоего поста на хабре.
https://habrahabr.ru/company/wolfram/blog/320196/
Прости, что слегка не по теме, но спросить больше не у кого.
Я написал простой сервер в файле test.wl и запускаю его через cmd команду 
$ wolfram -script test.wl
Вот только беда в том что судя документации ядро wolfram завершает свою работу прочитав последнюю строку файла.
То есть я создаю сервер и он тут же завершает работу.
Как быть в такой ситуации? Как заставить wolfram работать в фоновом режиме?

**Comment by KirillBelovTest** [comment]
### Пояснение

День добрый! Во-первых, хочу сказать, что вопрос действительно хороший и как раз по теме. Именно для этого *"приложения"* лучше всего подходит такой сценарий запуска - то есть старт из командной строки, что позволяет добавить скрипт запуска например в *cron*. Во-вторых, требуется пояснение, как именно вы хотите выполнять запуск? Чтобы процесс занимал текущий терминал, или запускался отдельно? Способов проделать все это много, как с помощью Математики, так и с помощью cmd/bash.

### Упрощенный пример сервера

В любой доступный директории создадим папку *MathServer* с файлом *MathServer.m*.

```
MathServer
----MathServer.m
```

В файл *MathServer.m* необходимо добавить следующий код: 

```mathematica
(* загрузка контекста для работы с сокетами *)
Get["SocketLink`"]; 

(* создание обработчика запросов *)
handler[{in_InputStream, out_OutputStream}] := 
Module[{request, response}, 
	
	request = FromCharacterCode[
		Reap[
			While[True, 
				TimeConstrained[Sow[BinaryRead[in]], 0.01, Break[]]
			]
		][[-1, -1]]
	]; 
	Print[request]; 
	
	Close[in]; 
	
	response = "Hello, World!"; 
	
	Print[response];
	 
	BinaryWrite[out, ToCharacterCode[response]]; 
	
	Close[out]; 
]; 

(* функция для запуска *)
startServer[port_Integer] := 
Module[{socket, server}, 

	socket = CreateServerSocket[port]; 
	server = CreateAsynchronousServer[socket, handler]; 
	{server, socket}
]; 

(* функция для остановки сервера *)
stopServer[{server_AsynchronousTaskObject, socket_Socket}] := 
(
	Sockets`CloseSocket[socket]; 
	StopAsynchronousTask[server]; 
); 

(* запуск сервера на указанном порте или 8888 *)
startServer[If[Length[$CommandLine] > 3, ToExpression[$CommandLine[[-1]]], 8888]]; 
Print["PID: ", $ProcessID]
```

### Запуск отдельным процессом

Для этого необходимо в директории *MathServer* запустить командную строку и выполнить такой код:

```
start wolfram -initfile MathServer.m 8888
```

В итоге откроется окно терминала, в котором запустится отельное ядро Математики. В этом ядре будет запущен сервер на указанном порте. При этом остановить сервер можно будет закрыв терминал, остановив процесс по распечатанному pid или прямо в терминале выполнив команду: 

```mathematica
stopServer[{server, socket}]
````

Все тоже самое должно сработать и для debian, только там кажется для запуска приложения в фоновом процессе нужно испольовать `app &`.

### Картинки

![2017-05-29 1](https://cloud.githubusercontent.com/assets/16749283/26541727/f8204418-4467-11e7-9b74-3cc7a9fd8cff.png)
*Выполнение запуска*

![2017-05-29 4](https://cloud.githubusercontent.com/assets/16749283/26541819/633f971c-4468-11e7-960d-3a9d9ab9acd9.png)
*Новое окно с запущенным ядром и напечатанный лог сервера*

![2017-05-29 3](https://cloud.githubusercontent.com/assets/16749283/26541833/735fec28-4468-11e7-98c6-cd0e8c3e1a7c.png)
*браузер*

**Comment by KirillBelovTest** [comment]
И еще, если у вас будут какие-то еще вопросы касательно приложения можете задавать их здесь или создать пост в русскоязычной поддержке: https://vk.com/wolframmathematica, где я тоже иногда отвечаю. Кроме того, если вас интересует работа с процессами и аргументами командной строки - ознокомтесь со следующими ссылка: 

http://reference.wolfram.com/language/ref/program/wolfram.html
https://reference.wolfram.com/language/ref/program/wolframscript.html
https://www.wolfram.com/wolframscript/
https://reference.wolfram.com/language/tutorial/WolframSystemSessions.html
